export const prompts = {
    "Rock": 
        ["Realistic vintage jukebox surrounded by electric guitars",
        "Watercolor painting of a rock n' roll stage with spotlights and a cheering crowd silhouette",
        "Abstract art of electric guitars floating in space among stars and planets",
        "Oil painting of a classic 1950s car driving on a vinyl record road",
        "Sketch of a rockstar's leather jacket with pins and patches draped over an amplifier",
        "Digital art of a dragon playing an electric guitar on top of a mountain",
        "Watercolor neon-lit city skyline with musical notes soaring upwards",
        "Realistic drawing of an astronaut playing a guitar on the moon with Earth in the background",
        "Impressionist painting of a phoenix rising from a flaming guitar",
        "Watercolor of a skeleton with a pompadour hairstyle playing a double-neck guitar",
        "Tattoo-style heart with wings and a banner surrounded by musical notes in a charcoal sketch",
        "Gouache painting of a microphone stand intertwined with roses and thorns",
        "Digital rendering of a lion with a rockstar mane roaring atop a stack of speakers",
        "Pastel drawing of an ocean wave transforming into musical notes as it crashes",
        "Retro diner scene in watercolor with tables in the shape of vinyl records",
        "Oil painting of a classic rock n' roll band performing inside of an hourglass",
        "Realistic turntable DJ booth surrounded by stone statues of rock legends",
        "Sketch in ink of a knight in armor holding an electric guitar like a sword",
        "Pop art of a silhouette of a mosh pit with hands reaching out to a glowing stage",
        "Watercolor of a classic boombox with wings soaring over a cityscape",
        "Graffiti wall with spray-painted guitars and drum sets in digital art form",
        "Oil painting of a vinyl record transforming into a phoenix mid-flight",
        "Desert landscape in watercolor with cacti shaped like musical notes",
        "Old school rock n' roll poster in acrylic paint with band instruments as the main focus",
        "Digital art of a pair of rockstar boots stepping on a cloud with lightning bolts",
        "Sketch of a music festival campsite with tents shaped like guitar picks",
        "Rock n' roll inspired dreamcatcher in watercolor with guitar picks and drumsticks",
        "Roller coaster track in the style of a charcoal drawing in the shape of a guitar neck",
        "Oil painting of rockstar's sunglasses reflecting a cheering concert crowd",
        "Realistic classic microphone surrounded by a halo of flames in digital art"],
    "Pop" : 
        [    "Realistic sparkling microphone on a glitzy pop stage",
        "Watercolor painting of a pop concert with glowing wristbands and cheering fans",
        "Abstract art of colorful headphones floating in a neon-lit cityscape",
        "Oil painting of a retro boombox amidst floating bubbles",
        "Sketch of a pop diva's glamorous high-heels beside a microphone stand",
        "Digital art of a dancing crowd under a shimmering disco ball",
        "Watercolor city skyline with musical notes transforming into balloons",
        "Realistic drawing of a turntable with vinyl reflecting colorful stage lights",
        "Impressionist painting of a young pop star singing under the spotlight",
        "Watercolor of a neon jukebox surrounded by floating vinyl records",
        "Tattoo-style heart entwined in a ribbon with musical notes in a charcoal sketch",
        "Gouache painting of a vibrant backstage dressing room with costumes and makeup",
        "Digital rendering of a synthesizer keyboard under a cascade of stars",
        "Pastel drawing of a festival crowd lit by stage pyrotechnics",
        "Retro diner jukebox in watercolor with pop songs title cards",
        "Oil painting of a trendy pop group taking a selfie together",
        "Realistic earbuds intertwined with a cascade of colorful candy",
        "Sketch in ink of a cassette tape unraveling into a dancing silhouette",
        "Pop art of a vintage TV showcasing a pop music video from the 80s",
        "Watercolor of a modern smartphone streaming a pop music video",
        "Digital art of a pair of trendy pop concert tickets on a vibrant background",
        "Oil painting of a romantic pop duet under a moonlit sky",
        "Beach party with colorful umbrellas and boomboxes in watercolor",
        "Pop star's signature hat and sunglasses in acrylic paint on a stage backdrop",
        "Digital art of a limousine pulling up to a red carpet event with popping flashbulbs",
        "Sketch of a VIP backstage pass hanging from a lanyard with pop motifs",
        "Pop music awards trophy in watercolor with spotlights shining down",
        "Stylized vinyl record player with pastel-colored records in the style of a charcoal drawing",
        "Oil painting of a pop star's diary filled with song lyrics and doodles",
        "Realistic concert poster peeling off a brick wall in digital art"],
    'Rap': [
        "Realistic golden microphone on an urban graffiti backdrop",
        "Watercolor painting of a rap battle in an underground club",
        "Abstract art of a cityscape with skyscrapers shaped like equalizers",
        "Oil painting of a boombox on a street corner with breakdancers",
        "Sketch of a rapper's iconic chain and pendant against a smoky background",
        "Digital art of a recording studio with headphones, mics, and mixers",
        "Watercolor of streetwear sneakers on a stairway tagged with graffiti",
        "Realistic drawing of a turntable with vinyl reflecting city lights",
        "Impressionist painting of a cypher with rappers showcasing their skills",
        "Watercolor of a cassette tape unravelling into a city skyline",
        "Charcoal sketch of a cap turned backwards with music notes escaping from it",
        "Gouache painting of an alleyway with murals paying tribute to rap legends",
        "Digital rendering of a stadium concert with fans swaying to rap beats",
        "Pastel drawing of a rap artist jotting down lyrics in a dimly lit room",
        "Retro gold chain and oversized sunglasses in watercolor on a velvet backdrop",
        "Oil painting of a rooftop rap session under a setting sun",
        "Realistic graffiti spray cans with vibrant paint splatters",
        "Sketch in ink of a car with oversized rims next to a crowd",
        "Pop art of a vintage radio broadcasting a rap show with dynamic waves",
        "Watercolor of a notebook filled with rap lyrics and doodles",
        "Digital art of a microphone with flames against a brick wall",
        "Oil painting of a rap concert with hands raised forming symbols",
        "Rap artist's studio with platinum records in watercolor",
        "Acrylic painting of a stage dive during a rap concert",
        "Digital art of a subway station with lyrics painted on the walls",
        "Sketch of a DJ mixing tracks with a hyped crowd in the background",
        "Rap-inspired dreamcatcher with pendants and charms in watercolor",
        "Stylized city skyline at night with moonlight shining on a rooftop party",
        "Oil painting of an urban bridge with rappers freestyling underneath",
        "Realistic tattoo design inspired by a rap song on parchment paper"
    ],
    'Jazz': [
        "Realistic vintage trumpet against a smoky club backdrop",
        "Watercolor painting of a jazz quartet under dimmed stage lights",
        "Abstract art of a double bass resonating vibrant colors",
        "Oil painting of a lively jazz street parade",
        "Sketch of a pianist's hands passionately playing on ivories",
        "Digital art of a jazz cafe scene with silhouette figures",
        "Watercolor of a saxophonist in an alleyway surrounded by neon lights",
        "Realistic drawing of a worn-out jazz vinyl on an old record player",
        "Impressionist painting of a female jazz singer lost in her song",
        "Watercolor of cobbled streets with jazz band performing at dusk",
        "Charcoal sketch of a vibraphone with mallets hovering above it",
        "Gouache painting of a smoky underground jazz club filled with patrons",
        "Digital rendering of a cityscape with skyscrapers shaped like musical instruments",
        "Pastel drawing of a clarinet with musical notes swirling around",
        "Noir-inspired watercolor scene of a jazz detective with a saxophone",
        "Oil painting of an intimate jazz duet on a moonlit rooftop",
        "Realistic jazz concert poster crumpled and left on a club floor",
        "Sketch in ink of a flapper dancer surrounded by jazz musicians",
        "Pop art of vintage jazz radio with soundwaves radiating outward",
        "Watercolor of a rainy evening with reflections of a jazz ensemble",
        "Digital art of a drummer in action with dynamic strokes visualizing rhythm",
        "Oil painting of an old jazz record store with patrons browsing",
        "Jazz instruments in a symphony with vibrant swirls in watercolor",
        "Acrylic painting of a jazz festival with colorful tents and lively crowds",
        "Digital art of a jazz cruise ship with silhouettes dancing on deck",
        "Sketch of a jazz guitarist deeply engrossed in a solo performance",
        "Elegant ballroom jazz dance in watercolor with flowing dresses",
        "Stylized gramophone emitting colorful soundwaves in the style of a charcoal drawing",
        "Oil painting of a jazz jam session in a cozy living room",
        "Realistic vintage jazz magazine cover with iconic artists in sepia tones"
    ],
    'Blues': [
        "Realistic vintage harmonica resting on a worn wooden table",
        "Watercolor painting of a blues guitarist playing under a southern sunset",
        "Abstract art of a blues singer, her voice visualized as waves of color",
        "Oil painting of a dusty crossroads with a lone musician",
        "Sketch of old, weathered hands playing a slide guitar",
        "Digital art of a juke joint with dancers and vibrant energy",
        "Watercolor of a moonlit bayou with the silhouette of a bluesman on a porch",
        "Realistic drawing of an old blues vinyl spinning on a gramophone",
        "Impressionist painting of a smoky blues club in the heart of Mississippi",
        "Watercolor of a worn-out delta shack radiating soulful melodies",
        "Charcoal sketch of a classic blues band set against a brick wall",
        "Gouache painting of a blues harmonica surrounded by floating notes",
        "Digital rendering of a neon-lit blues bar with patrons lost in music",
        "Pastel drawing of a pair of dancing shoes tapping to blues rhythm",
        "Chicago blues scene in watercolor with city skyline in the background",
        "Oil painting of a historic blues record label office",
        "Realistic aged concert ticket for a legendary blues performer",
        "Sketch in ink of a smoky train station with blues tunes in the air",
        "Pop art of vintage blues radio emitting soulful vibes",
        "Watercolor of an old bluesman sharing stories and tunes around a campfire",
        "Digital art of a blues festival stage set against a cotton field",
        "Oil painting of a rainy street with the echo of blues from a distant club",
        "Guitar case filled with memories and badges in watercolor",
        "Acrylic painting of a lively blues dance hall with swirling dresses",
        "Digital art of a blues riverboat cruising the Mississippi at dusk",
        "Sketch of a singer pouring her heart out at a blues cafe",
        "Delta blues scene in watercolor with marshlands and harmonica sounds",
        "Stylized blues notes flowing like a river in the style of a charcoal drawing",
        "Oil painting of a late-night blues jam in a dimly lit room",
        "Realistic portrait of a blues legend with soulful eyes and guitar in hand"
    ],
    'Classical': [
        "Realistic ornate violin resting on an antique music sheet",
        "Watercolor painting of a grand symphony orchestra in full swing",
        "Abstract art representing the powerful emotions of a classical overture",
        "Oil painting of an elegant ballroom with couples waltzing",
        "Sketch of a maestro's hands, gracefully directing a crescendo",
        "Digital art of a historic opera house with golden interiors and chandeliers",
        "Watercolor of a tranquil scene with a cello by a lakeside",
        "Realistic drawing of an old piano with ivory keys worn from time",
        "Impressionist painting of an opera diva belting a high note",
        "Watercolor of a classical quartet practicing in a sunlit conservatory",
        "Charcoal sketch of a grand concert hall bustling with anticipation",
        "Gouache painting of a baroque harpsichord with intricate designs",
        "Digital rendering of a dreamlike landscape inspired by a classical suite",
        "Pastel drawing of ballet dancers moving to a classical composition",
        "Renaissance fair with minstrels and lutes in watercolor",
        "Oil painting of a composer lost in thought, quill in hand",
        "Realistic aged sheet music for a timeless classical masterpiece",
        "Sketch in ink of an intimate chamber music performance",
        "Pop art of a vintage gramophone playing a classical record",
        "Watercolor of a moonlit castle with echoes of a classical serenade",
        "Digital art of a mythical scene inspired by a classical opera",
        "Oil painting of a musician tuning his viola before a performance",
        "Baroque-inspired ball in watercolor with masks and ornate costumes",
        "Acrylic painting of a child prodigy playing a sonata on the piano",
        "Digital art of a feather quill writing a classical score",
        "Sketch of an audience in rapt attention at a classical recital",
        "Romantic-era inspired landscape in watercolor with rolling hills and melodies",
        "Stylized classical instruments floating in the cosmos, drawn in charcoal",
        "Oil painting of a historic music conservatory with budding musicians",
        "Realistic busts of legendary classical composers set against a marble backdrop"
    ],
    'Country': [
        "Realistic weathered cowboy boots beside a vintage guitar",
        "Watercolor painting of a country barn dance under the stars",
        "Abstract art visualizing the soulful strum of a country ballad",
        "Oil painting of a rodeo with galloping horses and cheering crowds",
        "Sketch of a lone singer with a hat, silhouetted against a setting sun",
        "Digital art of a honky-tonk bar with neon signs and lively dancers",
        "Watercolor of a country fair with rides, flags, and music stages",
        "Realistic drawing of a banjo resting on a checkered picnic blanket",
        "Impressionist painting of a country duo performing on a porch",
        "Watercolor of a rustic saloon with musicians entertaining patrons",
        "Charcoal sketch of a tranquil countryside with musical notes in the wind",
        "Gouache painting of a vintage country radio set on a wooden table",
        "Digital rendering of a country festival with trucks, tents, and stages",
        "Pastel drawing of a line dance in motion with vibrant energy",
        "Nashville-inspired street scene in watercolor with music venues and signs",
        "Oil painting of a campfire jam session with guitars and harmonicas",
        "Realistic old country vinyl record with a rustic label design",
        "Sketch in ink of a fiddle player lost in the melody",
        "Pop art of a country jukebox selecting a golden era track",
        "Watercolor of a railroad with a musician traveling and playing songs",
        "Digital art of a country singer on a stage shaped like a guitar pick",
        "Oil painting of a sunset over a wheat field with a guitar silhouette",
        "Western bar scene in watercolor with cowboys and live music",
        "Acrylic painting of a country family gathering with music and dance",
        "Digital art of a country-themed tattoo design with musical elements",
        "Sketch of a harmonica emitting sound waves in a heart shape",
        "Country star's tour bus in watercolor traveling a scenic route",
        "Stylized silhouette of a country legend against a moonlit night, in charcoal",
        "Oil painting of a rustic wooden stage set for a country music fest",
        "Realistic portrait of a country icon with a signature hat and guitar"
    ],
    'EDM': [
        "Realistic neon-lit DJ booth with pulsating sound waves",
        "Watercolor painting of a rave with glowing wristbands and energetic dancers",
        "Abstract art visualizing the electronic beats of a dance track",
        "Oil painting of a music festival with laser lights cutting through the night",
        "Sketch of headphones emitting colorful musical notes and patterns",
        "Digital art of an underground electronic club with a vibrant dance floor",
        "Watercolor of futuristic cityscape pulsating to electronic beats",
        "Realistic drawing of a synthesizer with glowing keys and dials",
        "Impressionist painting of a DJ lost in the rhythm, surrounded by a euphoric crowd",
        "Watercolor of digital soundwaves merging with a natural landscape",
        "Charcoal sketch of a rave in a forest with fairy lights and dreamy visuals",
        "Gouache painting of a dance circle at an EDM beach party",
        "Digital rendering of an astronaut DJing in space with stars pulsating to beats",
        "Pastel drawing of a festival crowd, hands raised, under a neon sky",
        "Cyberpunk-inspired digital art scene with electronic music vibes",
        "Oil painting of a silent disco with dancers immersed in their own worlds",
        "Realistic LED screen displaying vibrant visuals at an EDM concert",
        "Sketch in ink of a DJ's hands manipulating a turntable with precision",
        "Pop art of vintage cassette tape remixing into electronic beats",
        "Watercolor of an EDM boat party cruising under a vibrant sunset",
        "Digital art of a holographic DJ performing in a futuristic city square",
        "Oil painting of a desert transformed into an EDM oasis with stages and tents",
        "Robot DJing in a post-apocalyptic scene in watercolor",
        "Acrylic painting of a neon-lit tunnel with dancers moving to trance beats",
        "Digital art of a virtual reality EDM concert with 3D visuals",
        "Sketch of an electronic sound mixer surrounded by ethereal lights",
        "Futuristic sound lab in watercolor with dials, screens, and beats",
        "Stylized vinyl record floating in a digital matrix in charcoal",
        "Oil painting of a mountaintop rave under the aurora borealis",
        "Realistic pair of electronic gloves, orchestrating music in a digital realm"
    ],
    'R&B': [
        "Realistic vintage microphone with sultry red stage curtains",
        "Watercolor painting of a soulful singer under a single spotlight",
        "Abstract art visualizing the smooth rhythms of an R&B ballad",
        "Oil painting of a rooftop serenade under city lights",
        "Sketch of a romantic couple dancing closely to an R&B track",
        "Digital art of a retro diner with a jukebox playing soulful hits",
        "Watercolor of an intimate concert in a smoky, dimly lit lounge",
        "Realistic drawing of vinyl records with iconic R&B album covers",
        "Impressionist painting of a jazz club transitioning into an R&B scene",
        "Watercolor of urban streets with musical notes flowing from windows",
        "Charcoal sketch of a lone saxophonist playing a soulful tune at dusk",
        "Gouache painting of a 60s R&B group harmonizing on stage",
        "Digital rendering of neon-lit urban streets inspired by R&B vibes",
        "Pastel drawing of a vintage car radio tuning into an R&B station",
        "Motown-inspired digital art scene with singers, dancers, and bands",
        "Oil painting of a moonlit beach with soft R&B melodies in the air",
        "Realistic vintage concert poster advertising an R&B legend's performance",
        "Sketch in ink of a singer pouring heart and soul into a microphone",
        "Pop art of a cassette tape with colorful R&B vibes emanating",
        "Watercolor of an urban park jam session centered around R&B rhythms",
        "Digital art of an R&B album recording session behind the scenes",
        "Oil painting of a serene bedroom with an R&B playlist setting the mood",
        "Gramophone in a modern setting playing R&B classics in watercolor",
        "Acrylic painting of a dance studio with couples practicing to R&B beats",
        "Digital art of a vintage TV broadcasting classic R&B performances",
        "Sketch of an R&B artist's diary filled with lyrics and memories",
        "Lush rooftop garden party under stars with R&B music in watercolor",
        "Stylized boombox with soulful soundwaves in the style of a charcoal drawing",
        "Oil painting of a sunset concert with R&B artists on stage",
        "Realistic golden headphones radiating soft R&B melodies in a tranquil room"
    ],
    'Soul': [
        "Realistic vintage record player spinning a soulful track",
        "Watercolor painting of a soul singer pouring emotion into every note",
        "Abstract art capturing the essence and depth of soul music",
        "Oil painting of a choir delivering a powerful soul performance in church",
        "Sketch of a heart-shaped vinyl representing the core of soul music",
        "Digital art of a smoky bar with a singer channeling raw soulful vibes",
        "Watercolor of a jazz club lit by candles, transitioning into a soul night",
        "Realistic drawing of a soul legend's iconic outfit and accessories",
        "Impressionist painting of a passionate soul duet under city lights",
        "Watercolor of a dreamy moonlit scene with soul melodies in the air",
        "Charcoal sketch of a classic 60s soul group performing on a TV show",
        "Gouache painting of an urban setting with soul tunes echoing from open windows",
        "Digital rendering of a recording studio capturing pure soul magic",
        "Pastel drawing of a romantic dance with soul music setting the mood",
        "Motown-inspired scene in digital art with vibrant colors and energy",
        "Oil painting of a serene lakeside bonfire with soulful guitar tunes",
        "Realistic sheet music of a timeless soul hit with handwritten notes",
        "Sketch in ink of a pianist lost in the soulful rhythm and melodies",
        "Pop art of a vintage concert poster promoting a soul music festival",
        "Watercolor of a tranquil garden scene with soft soul music playing",
        "Digital art of a soul musician's dream, filled with symbols and memories",
        "Oil painting of a vinyl store's soul section with iconic album covers",
        "Intimate home concert of a soul artist in watercolor",
        "Acrylic painting of a city bus with passengers lost in soulful thoughts",
        "Digital art of a radio emanating colorful waves to a soul rhythm",
        "Sketch of a retro microphone with soulful aura and ambiance",
        "Night sky filled with stars forming soul music icons in watercolor",
        "Stylized gramophone in a modern setting with soul vibes, drawn in charcoal",
        "Oil painting of a carnival scene with soul music on the main stage",
        "Realistic headphones on an armchair, capturing a soulful escape"
    ],
    'Heavy Metal': [
        "Realistic electric guitar engulfed in roaring flames",
        "Watercolor painting of a metal concert with headbanging fans",
        "Abstract art capturing the raw energy and power of heavy metal music",
        "Oil painting of a mythical beast inspired by iconic metal album covers",
        "Sketch of a leather-clad metal guitarist delivering a piercing solo",
        "Digital art of a post-apocalyptic landscape with metal sound waves",
        "Watercolor of an ancient castle with a metal band performing atop its walls",
        "Realistic drawing of a studded wristband and iconic metal memorabilia",
        "Impressionist painting of a metal festival under a stormy sky",
        "Watercolor of a phantom ship sailing the seas with a metal anthem",
        "Charcoal sketch of a metal vocalist releasing a powerful scream",
        "Gouache painting of a dystopian cityscape inspired by metal themes",
        "Digital rendering of a medieval battlefield with warriors and metal tunes",
        "Pastel drawing of an enigmatic metal sorceress with a guitar staff",
        "Gothic cathedral in digital art with stained glass showcasing metal legends",
        "Oil painting of a dense forest with a secret metal concert",
        "Realistic ancient scroll depicting a legendary metal tale",
        "Sketch in ink of a drummer in action amidst a blaze of pyrotechnics",
        "Pop art of a vintage amplifier with electrifying metal vibes",
        "Watercolor of a desolate mountain peak with the echo of metal riffs",
        "Digital art of a cyberpunk city with metal graffiti and neon lights",
        "Oil painting of a metal band performing in the ruins of a coliseum",
        "Viking longship in watercolor sailing to the rhythm of heavy metal",
        "Acrylic painting of a space odyssey inspired by progressive metal",
        "Digital art of a fortress guarded by armored knights with metal insignias",
        "Sketch of a roaring dragon intertwined with a metal guitar",
        "Desert wasteland with metal warriors in watercolor",
        "Stylized phoenix rising from a guitar, drawn in charcoal for a metal rebirth",
        "Oil painting of a cosmic portal with celestial beings enjoying metal tunes",
        "Realistic battle-worn armor reflecting a blazing metal concert"
    ],
    'Punk': [
        "Realistic graffiti-covered electric guitar with punk stickers",
        "Watercolor painting of a mosh pit in an underground punk club",
        "Abstract art expressing the rebellious energy of punk rock",
        "Oil painting of a punk rocker with a colorful mohawk on city streets",
        "Sketch of worn-out combat boots and a studded leather jacket",
        "Digital art of a post-apocalyptic punk sanctuary with DIY ethos",
        "Watercolor of a rooftop punk gig amidst skyscrapers",
        "Realistic drawing of a vintage punk band poster plastered on a wall",
        "Impressionist painting of a punk concert in a squatted building",
        "Watercolor of an urban alley with punk lyrics spray-painted all over",
        "Charcoal sketch of a bassist lost in the rhythm of a punk anthem",
        "Gouache painting of a punk's makeshift bedroom filled with posters and records",
        "Digital rendering of a subway station turned into an impromptu punk show",
        "Pastel drawing of a punk's patch-covered backpack with pins and badges",
        "Anarchist's utopia in digital art inspired by punk ideologies",
        "Oil painting of a record store's punk section with underground zines",
        "Realistic tattoo design inked with punk symbols and imagery",
        "Sketch in ink of a drummer performing amidst flying bottles and stage dives",
        "Pop art of a retro cassette tape with a punk mixtape label",
        "Watercolor of a DIY punk venue with handmade stage and lighting",
        "Digital art of a dystopian city with punk rebels leading a movement",
        "Oil painting of a seaside punk festival with bonfires and tents",
        "Skatepark scene in watercolor with punk skaters and musicians",
        "Acrylic painting of a road trip in a van filled with punk band members",
        "Digital art of a fortress with punk flags and murals",
        "Sketch of a punk singer gripping the mic with fierce intensity",
        "Abandoned warehouse turned punk haven in watercolor",
        "Stylized broken guitar strings representing punk's raw essence in charcoal",
        "Oil painting of a moonlit punk gathering in an ancient graveyard",
        "Realistic worn-out vinyl record of a legendary punk album on a turntable"
    ], 
    
    
    
    
    


    };