export const prompts = {
    "Rock": [
        "Electric guitar on fire against a dark stormy sky.",
        "Rock hand gesture forming from a mountain peak.",
        "Lightning bolts striking a set of drums.",
        "Grungy urban alleyway with shadowy figures holding instruments.",
        "Lion roaring with a mane made of guitar strings.",
        "Skull wearing aviator glasses amidst a rock concert crowd.",
        "Monochrome silhouette of a crowd with raised fists.",
        "Vintage amplifier amidst a forest of thorns.",
        "Tattooed hand holding a pick, ready to strum.",
        "Dramatic cliffside with a lone guitarist playing.",
        "Studded leather jacket with musical note patterns.",
        "Rock band performing atop a floating island.",
        "Stonehenge-like structure with instruments as stones.",
        "Graffiti wall with the word 'ROCK' in fiery letters.",
        "Motorbike racing on a path made of piano keys.",
        "Distorted guitar reflection in a pool of water.",
        "Volcano erupting with musical notes instead of lava.",
        "Desert landscape with cacti shaped like guitars.",
        "Giant rock eagle soaring over a concert stage.",
        "Rusty microphone entwined in vines.",
        "Screaming face morphing into an electric guitar.",
        "Fiery phoenix playing drums in mid-flight.",
        "Retro van with painted murals of rock legends.",
        "Crumbling ancient statue holding a modern guitar.",
        "Rock 'n roll vinyl record spinning on a turntable.",
        "Guitar pick with intricate tribal carvings.",
        "Mosh pit forming the shape of a heart.",
        "Cave paintings depicting a rock concert.",
        "Jukebox in a rugged bar with a neon 'Rock' sign.",
        "Sunset skyline with skyscrapers as equalizer bars."
    ],
};